# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0007_subjectmatterexpert_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='small_image',
            field=models.ImageField(blank=True, upload_to=b'photos/%Y/%m/%d'),
        ),
    ]
